// <auto-generated />
namespace mobileshop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class FixedModelMismatch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedModelMismatch));
        
        string IMigrationMetadata.Id
        {
            get { return "202602080224173_FixedModelMismatch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
